using UnityEngine;

/// <summary>
/// An objective generated by the hunter. A Boid can detect it locally and
/// interact with it using Arrive. Its life is intentionally visible so the
/// interaction can be verified while the simulation is running.
/// </summary>
public class InterestObject : MonoBehaviour
{
    [SerializeField] private float maxLife = 4f;

    private float life;
    private float flashTimer;
    private Renderer objectRenderer;
    private Collider objectCollider;

    public float Life => life;
    public float MaxLife => maxLife;
    public bool IsAvailable { get; private set; }

    private void Awake()
    {
        objectRenderer = GetComponent<Renderer>();
        objectCollider = GetComponent<Collider>();
        life = maxLife;
        IsAvailable = true;
        UpdateVisual();
    }

    public void Initialize(float startingLife)
    {
        maxLife = Mathf.Max(0.1f, startingLife);
        life = maxLife;
        IsAvailable = true;

        if (objectRenderer == null)
        {
            objectRenderer = GetComponent<Renderer>();
        }

        if (objectCollider == null)
        {
            objectCollider = GetComponent<Collider>();
        }

        SetVisible(true);
        UpdateVisual();
    }

    private void Update()
    {
        if (flashTimer > 0f)
        {
            flashTimer -= Time.deltaTime;
            if (objectRenderer != null && IsAvailable)
            {
                objectRenderer.material.color = Color.white;
            }

            if (flashTimer <= 0f)
            {
                UpdateVisual();
            }
        }
    }

    public bool ReceiveDamage(float amount)
    {
        if (!IsAvailable)
        {
            return false;
        }

        life = Mathf.Max(0f, life - Mathf.Max(0f, amount));
        flashTimer = 0.12f;

        if (objectRenderer != null)
        {
            objectRenderer.material.color = Color.white;
        }

        if (life <= 0f)
        {
            IsAvailable = false;
            SetVisible(false);
        }
        else
        {
            UpdateVisual();
        }

        return true;
    }

    private void SetVisible(bool visible)
    {
        if (objectRenderer != null)
        {
            objectRenderer.enabled = visible;
        }

        if (objectCollider != null)
        {
            objectCollider.enabled = visible;
        }
    }

    private void UpdateVisual()
    {
        if (objectRenderer == null || !IsAvailable)
        {
            return;
        }

        float normalizedLife = Mathf.Clamp01(life / Mathf.Max(0.01f, maxLife));
        objectRenderer.material.color = Color.Lerp(
            new Color(0.95f, 0.22f, 0.16f),
            new Color(1f, 0.78f, 0.1f),
            normalizedLife);
    }
}
